version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: mysql/dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gochatapp
      MYSQL_USER: enomoto
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - "db-data:/var/lib/mysql"
      - ./mysql/my.conf:/etc/mysql/conf.d/my.conf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-api-db-net
  web:
    build:
      context: .
      dockerfile: web-server/docker/app/dockerfile
    ports:
      - "80:80"
    volumes:
     - ./web-server:/go/src/go-chat-app-api-ver
    networks: 
      - app-api-db-net
  api:
    build:
      context: .
      dockerfile: chat-api/docker/api/dockerfile
    ports:
      - "8080:80"
    volumes:
     - .:/api
    networks: 
      - app-api-db-net

volumes:
  db-data:
    driver: local

networks:
  app-api-db-net:
    driver: bridge