swagger: "2.0"
info:
  title: Chat Service
  description: Service for chat app, a Goa teaser
  version: ""
host: 172.25.0.3:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /chatroom/{id}:
    get:
      tags:
      - chatapi
      summary: getchat chatapi
      operationId: chatapi#getchat
      parameters:
      - name: id
        in: path
        description: room id
        required: true
        type: integer
      - name: Authorization
        in: header
        description: API key used to perform authorization
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChatapiGoaChatResponseCollection'
      schemes:
      - http
      security:
      - api_key_header_Authorization: []
definitions:
  ChatapiGoaChatResponseCollection:
    title: 'Mediatype identifier: application/vnd.goa.chat; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/GoaChatResponse'
    description: GetchatResponseBody is the result type for an array of GoaChatResponse
      (default view)
    example:
    - Chat: Rerum ut praesentium explicabo itaque sit ducimus.
      Id: 681183766627976715
      Member: Molestiae sed officiis eum earum esse aliquam.
      PostDt: "1990-09-09T14:12:10Z"
      RoomName: Quisquam consequatur culpa et aut ut.
      UserId: Ex error voluptatem corporis quas.
    - Chat: Rerum ut praesentium explicabo itaque sit ducimus.
      Id: 681183766627976715
      Member: Molestiae sed officiis eum earum esse aliquam.
      PostDt: "1990-09-09T14:12:10Z"
      RoomName: Quisquam consequatur culpa et aut ut.
      UserId: Ex error voluptatem corporis quas.
    - Chat: Rerum ut praesentium explicabo itaque sit ducimus.
      Id: 681183766627976715
      Member: Molestiae sed officiis eum earum esse aliquam.
      PostDt: "1990-09-09T14:12:10Z"
      RoomName: Quisquam consequatur culpa et aut ut.
      UserId: Ex error voluptatem corporis quas.
  GoaChatResponse:
    title: 'Mediatype identifier: application/vnd.goa.chat; view=default'
    type: object
    properties:
      Chat:
        type: string
        description: chat
        example: Est non neque.
      Id:
        type: integer
        description: room id
        example: 6560887464849577627
        format: int64
      Member:
        type: string
        description: member
        example: Exercitationem ut.
      PostDt:
        type: string
        example: "1984-02-15T19:55:47Z"
        format: date-time
      RoomName:
        type: string
        description: room name
        example: Aspernatur et nihil ab sint voluptas.
      UserId:
        type: string
        description: user id
        example: Consequatur accusamus.
    description: All chat (default view)
    example:
      Chat: Neque nostrum et magni eos enim.
      Id: 4335096105350829226
      Member: Quis repudiandae perferendis ut.
      PostDt: "1992-12-18T10:41:25Z"
      RoomName: Veritatis est.
      UserId: Voluptas perferendis.
    required:
    - Id
    - UserId
    - RoomName
    - Member
    - Chat
    - PostDt
securityDefinitions:
  api_key_header_Authorization:
    type: apiKey
    description: Secures endpoint by requiring an API key.
    name: Authorization
    in: header
